name: Crear y usar artefacto

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2

    - name: Crear carpeta de salida
      run: mkdir dist

    - name: Crear un archivo en la carpeta de salida
      run: echo "Contenido del archivo" > dist/ejemplo.txt

    - name: Guardar artefacto
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dist

  use-artifact:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: downloaded-artifact

    - name: Mostrar contenido del artefacto descargado
      run: cat downloaded-artifact/ejemplo.txt

